Revert "Homework 05"
Otus-DevOps-2017-11/artemsurov_infra pull request #2
Opened 2017-12-24 19:47 UTC by artemsurov

Reverts Otus-DevOps-2017-11/artemsurov_infra#1

2017-12-25 08:25 UTC, artemsurov commented
К сожалению, предыдущее, я смерджил не глядя(

2017-12-25 08:26 UTC, Nklya commented
А дифф этого PR ты видел?

2017-12-25 14:48 UTC, Nklya requested changes
Артем, смысл проверки через PR состоит в том, что работа ведется в отдельном бранче, в данном случае Infra-1 и потом делается Pull Request к ветке мастер.

Сейчас ты сделал PR наоборот. После его принятия наоборот все удалится.

Поэтому этот PR неправильный чуть более, чем полностью.

Самое простое, что можно сделать, это почистить мастер и делать новый PR, чтобы все изменения были отражены в нем

2018-01-01 18:15 UTC, artemsurov commented
окей)

2018-01-01 18:15 UTC, closed without merging