Terraform 2
Otus-DevOps-2017-11/artemsurov_infra pull request #7
Opened 2018-01-14 21:17 UTC by artemsurov

Домашние задание №9
Выполнил основное задание и первое задание со звездочкой

2018-01-15 21:09 UTC, Nklya requested changes
Добрый вечер.

Артем, практически все сделано хорошо. Особенно генерация имен бакетов)

Нужно исправить несколько проблем:
1. Вычистить из папки VPN какой-то шаблон пакера, который туда попал.
2. terraform.tfvars.example скопировать в папки stage и prod
3. В terraform/variables.tf сейчас есть лишние переменные, которые не используются той конфигурацией, которая лежит в папке терраформ. Их нужно удалить. И заодно актуализировать terraform/terraform.tfvars.example

2018-01-15 21:09 UTC, Nklya commented on VPN/ubuntu160.json
> +{
А что это?

2018-01-15 21:09 UTC, Nklya commented on terraform/storage_bucket.tf
> +name = ["storage-bucket-test-${sha1(timestamp())}", "storage-bucket-test2-${sha1(timestamp())}"]
Прикольное решение уникального имени))

2018-01-15 21:09 UTC, Nklya commented on terraform/modules/app/variables.tf
> +variable private_key {
А зачем этому модулю приватный ключ, если ты его не используешь?

2018-01-21 22:08 UTC, artemsurov commented on terraform/storage_bucket.tf
> +name = ["storage-bucket-test-${sha1(timestamp())}", "storage-bucket-test2-${sha1(timestamp())}"]
Спасибо)

2018-01-21 22:09 UTC, artemsurov commented
@Nklya Спасибо за ревью. Внес изменения в соответствии с замечаниями.

2018-01-22 11:15 UTC, Nklya approved these changes
Да, сейчас все хорошо.

2018-01-22 11:29 UTC, merged