Ansible 1
Otus-DevOps-2017-11/artemsurov_infra pull request #8
Opened 2018-01-15 21:59 UTC by artemsurov

Ваполнил домашнюю работу №10 и  задание со звездочкой.

2018-01-18 12:04 UTC, Nklya requested changes
Ревью после мержа предыдущего.

2018-01-22 11:30 UTC, artemsurov commented
Выполнил merge

2018-01-22 14:58 UTC, Nklya approved these changes
Добрый вечер.

Артем, условия дз выполнены, все выглядит ок.
👍

2018-01-22 14:58 UTC, merged

2018-01-22 14:58 UTC, Nklya commented
Смержил, т.к. мешает проверять дальше